# Generated by Django 5.0.4 on 2024-04-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkingspace',
            fields=[
                ('parkingid', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.FloatField(max_length=20)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availablestatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parkingid', models.IntegerField(max_length=40)),
                ('endtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('userid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=40)),
                ('reviewid', models.BigAutoField(primary_key=True, serialize=False)),
                ('parkingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.reservation')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.user'),
        ),
    ]
